INSERT INTO NUTS_D (nuts_III,concelho) values ('Alto Minho','Arcos de Valdevez')
,('Alto Minho','Caminha')
,('Alto Minho','Melgaço')
,('Alto Minho','Monção')
,('Alto Minho','Paredes de Coura')
,('Alto Minho','Ponte da Barca')
,('Alto Minho','Ponte de Lima')
,('Alto Minho','Valença')
,('Alto Minho','Viana do Castelo')
,('Alto Minho','Vila Nova de Cerveira')
,('Cávado','Amares')
,('Cávado','Barcelos')
,('Cávado','Braga')
,('Cávado','Esposende')
,('Cávado','Terras de Bouro')
,('Cávado','Vila Verde')
,('Ave','Cabeceiras de Basto')
,('Ave','Fafe')
,('Ave','Guimarães')
,('Ave','Mondim de Basto')
,('Ave','Póvoa de Lanhoso')
,('Ave','Vieira do Minho')
,('Ave','Vila Nova de Famalicão')
,('Ave','Vizela')
,('Área Metropolitana do Porto','Arouca')
,('Área Metropolitana do Porto','Espinho')
,('Área Metropolitana do Porto','Gondomar')
,('Área Metropolitana do Porto','Maia')
,('Área Metropolitana do Porto','Matosinhos')
,('Área Metropolitana do Porto','Oliveira de Azeméis')
,('Área Metropolitana do Porto','Paredes')
,('Área Metropolitana do Porto','Porto')
,('Área Metropolitana do Porto','Póvoa de Varzim')
,('Área Metropolitana do Porto','Santa Maria da Feira')
,('Área Metropolitana do Porto','Santo Tirso')
,('Área Metropolitana do Porto','São João da Madeira')
,('Área Metropolitana do Porto','Trofa')
,('Área Metropolitana do Porto','Vale de Cambra')
,('Área Metropolitana do Porto','Valongo')
,('Área Metropolitana do Porto','Vila do Conde')
,('Área Metropolitana do Porto','Vila Nova de Gaia')
,('Tâmega e Sousa','Amarante')
,('Tâmega e Sousa','Baião')
,('Tâmega e Sousa','Castelo de Paiva')
,('Tâmega e Sousa','Celorico de Basto')
,('Tâmega e Sousa','Cinfães')
,('Tâmega e Sousa','Felgueiras')
,('Tâmega e Sousa','Lousada')
,('Tâmega e Sousa','Marco de Canaveses')
,('Tâmega e Sousa','Paços de Ferreira')
,('Tâmega e Sousa','Penafiel')
,('Tâmega e Sousa','Resende')
,('Alto Tâmega','Boticas')
,('Alto Tâmega','Chaves')
,('Alto Tâmega','Montalegre')
,('Alto Tâmega','Ribeira de Pena')
,('Alto Tâmega','Valpaços')
,('Alto Tâmega','Vila Pouca de Aguiar')
,('Douro','Alijó')
,('Douro','Armamar')
,('Douro','Carrazeda de Ansiães')
,('Douro','Freixo de Espada à Cinta')
,('Douro','Lamego')
,('Douro','Mesão Frio')
,('Douro','Moimenta da Beira')
,('Douro','Murça')
,('Douro','Penedono')
,('Douro','Peso da Régua')
,('Douro','Sabrosa')
,('Douro','Santa Marta de Penaguião')
,('Douro','São João da Pesqueira')
,('Douro','Sernancelhe')
,('Douro','Tabuaço')
,('Douro','Tarouca')
,('Douro','Torre de Moncorvo')
,('Douro','Vila Nova de Foz Côa')
,('Douro','Vila Real')
,('Terras de Trás-os-Montes','Alfândega da Fé')
,('Terras de Trás-os-Montes','Bragança')
,('Terras de Trás-os-Montes','Macedo de Cavaleiros')
,('Terras de Trás-os-Montes','Miranda do Douro')
,('Terras de Trás-os-Montes','Mirandela')
,('Terras de Trás-os-Montes','Mogadouro')
,('Terras de Trás-os-Montes','Vila Flor')
,('Terras de Trás-os-Montes','Vimioso')
,('Terras de Trás-os-Montes','Vinhais')
,('Região de Aveiro','Águeda')
,('Região de Aveiro','Albergaria-a-Velha')
,('Região de Aveiro','Anadia')
,('Região de Aveiro','Aveiro')
,('Região de Aveiro','Estarreja')
,('Região de Aveiro','Ílhavo')
,('Região de Aveiro','Murtosa')
,('Região de Aveiro','Oliveira do Bairro')
,('Região de Aveiro','Ovar')
,('Região de Aveiro','Sever do Vouga')
,('Região de Aveiro','Vagos')
,('Região de Coimbra','Arganil')
,('Região de Coimbra','Cantanhede')
,('Região de Coimbra','Coimbra')
,('Região de Coimbra','Condeixa-a-Nova')
,('Região de Coimbra','Figueira da Foz')
,('Região de Coimbra','Góis')
,('Região de Coimbra','Lousã')
,('Região de Coimbra','Mealhada')
,('Região de Coimbra','Mira')
,('Região de Coimbra','Miranda do Corvo')
,('Região de Coimbra','Montemor-o-Velho')
,('Região de Coimbra','Mortágua')
,('Região de Coimbra','Oliveira do Hospital')
,('Região de Coimbra','Pampilhosa da Serra')
,('Região de Coimbra','Penacova')
,('Região de Coimbra','Penela')
,('Região de Coimbra','Soure')
,('Região de Coimbra','Tábua')
,('Região de Coimbra','Vila Nova de Poiares')
,('Região de Leiria','Batalha')
,('Região de Leiria','Leiria')
,('Região de Leiria','Marinha Grande')
,('Região de Leiria','Pombal')
,('Região de Leiria','Porto de Mós')
,('Região de Leiria','Alvaiázere')
,('Região de Leiria','Ansião')
,('Região de Leiria','Castanheira de Pera')
,('Região de Leiria','Figueiró dos Vinhos')
,('Região de Leiria','Pedrógão Grande')
,('Viseu Dão-Lafões','Aguiar da Beira')
,('Viseu Dão-Lafões','Carregal do Sal')
,('Viseu Dão-Lafões','Castro Daire')
,('Viseu Dão-Lafões','Mangualde')
,('Viseu Dão-Lafões','Nelas')
,('Viseu Dão-Lafões','Oliveira de Frades')
,('Viseu Dão-Lafões','Penalva do Castelo')
,('Viseu Dão-Lafões','Santa Comba Dão')
,('Viseu Dão-Lafões','São Pedro do Sul')
,('Viseu Dão-Lafões','Sátão')
,('Viseu Dão-Lafões','Tondela')
,('Viseu Dão-Lafões','Vila Nova de Paiva')
,('Viseu Dão-Lafões','Viseu')
,('Viseu Dão-Lafões','Vouzela')
,('Beiras e Serra da Estrela','Almeida')
,('Beiras e Serra da Estrela','Belmonte')
,('Beiras e Serra da Estrela','Celorico da Beira')
,('Beiras e Serra da Estrela','Covilhã')
,('Beiras e Serra da Estrela','Figueira de Castelo Rodrigo')
,('Beiras e Serra da Estrela','Fornos de Algodres')
,('Beiras e Serra da Estrela','Fundão')
,('Beiras e Serra da Estrela','Gouveia')
,('Beiras e Serra da Estrela','Guarda')
,('Beiras e Serra da Estrela','Manteigas')
,('Beiras e Serra da Estrela','Mêda')
,('Beiras e Serra da Estrela','Pinhel')
,('Beiras e Serra da Estrela','Sabugal')
,('Beiras e Serra da Estrela','Seia')
,('Beiras e Serra da Estrela','Trancoso')
,('Beira Baixa','Castelo Branco')
,('Beira Baixa','Idanha-a-Nova')
,('Beira Baixa','Oleiros')
,('Beira Baixa','Penamacor')
,('Beira Baixa','Proença-a-Nova')
,('Beira Baixa','Vila Velha de Ródão')
,('Oeste','Alcobaça')
,('Oeste','Alenquer')
,('Oeste','Arruda dos Vinhos')
,('Oeste','Bombarral')
,('Oeste','Cadaval')
,('Oeste','Caldas da Rainha')
,('Oeste','Lourinhã')
,('Oeste','Nazaré')
,('Oeste','Óbidos')
,('Oeste','Peniche')
,('Oeste','Sobral de Monte Agraço')
,('Oeste','Torres Vedras')
,('Médio Tejo','Abrantes')
,('Médio Tejo','Alcanena')
,('Médio Tejo','Constância')
,('Médio Tejo','Entroncamento')
,('Médio Tejo','Ferreira do Zêzere')
,('Médio Tejo','Mação')
,('Médio Tejo','Ourém')
,('Médio Tejo','Sardoal')
,('Médio Tejo','Sertã')
,('Médio Tejo','Tomar')
,('Médio Tejo','Torres Novas')
,('Médio Tejo','Vila de Rei')
,('Médio Tejo','Vila Nova da Barquinha')
,('Área Metropolitana de Lisboa','Alcochete')
,('Área Metropolitana de Lisboa','Almada')
,('Área Metropolitana de Lisboa','Amadora')
,('Área Metropolitana de Lisboa','Barreiro')
,('Área Metropolitana de Lisboa','Cascais')
,('Área Metropolitana de Lisboa','Lisboa')
,('Área Metropolitana de Lisboa','Loures')
,('Área Metropolitana de Lisboa','Mafra')
,('Área Metropolitana de Lisboa','Moita')
,('Área Metropolitana de Lisboa','Montijo')
,('Área Metropolitana de Lisboa','Odivelas')
,('Área Metropolitana de Lisboa','Oeiras')
,('Área Metropolitana de Lisboa','Palmela')
,('Área Metropolitana de Lisboa','Seixal')
,('Área Metropolitana de Lisboa','Sesimbra')
,('Área Metropolitana de Lisboa','Setúbal')
,('Área Metropolitana de Lisboa','Sintra')
,('Área Metropolitana de Lisboa','Vila Franca de Xira')
,('Lezíria do Tejo','Almeirim')
,('Lezíria do Tejo','Alpiarça')
,('Lezíria do Tejo','Azambuja')
,('Lezíria do Tejo','Benavente')
,('Lezíria do Tejo','Cartaxo')
,('Lezíria do Tejo','Chamusca')
,('Lezíria do Tejo','Coruche')
,('Lezíria do Tejo','Golegã')
,('Lezíria do Tejo','Rio Maior')
,('Lezíria do Tejo','Salvaterra de Magos')
,('Lezíria do Tejo','Santarém')
,('Alentejo Litoral','Alcácer do Sal')
,('Alentejo Litoral','Grândola')
,('Alentejo Litoral','Odemira')
,('Alentejo Litoral','Santiago do Cacém')
,('Alentejo Litoral','Sines')
,('Alto Alentejo','Alter do Chão')
,('Alto Alentejo','Arronches')
,('Alto Alentejo','Avis')
,('Alto Alentejo','Campo Maior')
,('Alto Alentejo','Castelo de Vide')
,('Alto Alentejo','Crato')
,('Alto Alentejo','Elvas')
,('Alto Alentejo','Fronteira')
,('Alto Alentejo','Gavião')
,('Alto Alentejo','Marvão')
,('Alto Alentejo','Monforte')
,('Alto Alentejo','Nisa')
,('Alto Alentejo','Ponte de Sor')
,('Alto Alentejo','Portalegre')
,('Alto Alentejo','Sousel')
,('Alentejo Central','Alandroal')
,('Alentejo Central','Arraiolos')
,('Alentejo Central','Borba')
,('Alentejo Central','Estremoz')
,('Alentejo Central','Évora')
,('Alentejo Central','Montemor-o-Novo')
,('Alentejo Central','Mora')
,('Alentejo Central','Mourão')
,('Alentejo Central','Portel')
,('Alentejo Central','Redondo')
,('Alentejo Central','Reguengos de Monsaraz')
,('Alentejo Central','Vendas Novas')
,('Alentejo Central','Viana do Alentejo')
,('Alentejo Central','Vila Viçosa')
,('Baixo Alentejo','Aljustrel')
,('Baixo Alentejo','Almodôvar')
,('Baixo Alentejo','Alvito')
,('Baixo Alentejo','Barrancos')
,('Baixo Alentejo','Beja')
,('Baixo Alentejo','Castro Verde')
,('Baixo Alentejo','Cuba')
,('Baixo Alentejo','Ferreira do Alentejo')
,('Baixo Alentejo','Mértola')
,('Baixo Alentejo','Moura')
,('Baixo Alentejo','Ourique')
,('Baixo Alentejo','Serpa')
,('Baixo Alentejo','Vidigueira')
,('Algarve','Albufeira')
,('Algarve','Alcoutim')
,('Algarve','Aljezur')
,('Algarve','Castro Marim')
,('Algarve','Faro')
,('Algarve','Lagoa')
,('Algarve','Lagos')
,('Algarve','Loulé')
,('Algarve','Monchique')
,('Algarve','Olhão')
,('Algarve','Portimão')
,('Algarve','São Brás de Alportel')
,('Algarve','Silves')
,('Algarve','Tavira')
,('Algarve','Vila do Bispo')
,('Algarve','Vila Real de Santo António')
,('Região Autónoma dos Açores','Angra do Heroísmo')
,('Região Autónoma dos Açores','Calheta')
,('Região Autónoma dos Açores','Corvo')
,('Região Autónoma dos Açores','Horta')
,('Região Autónoma dos Açores','Lagoa')
,('Região Autónoma dos Açores','Lajes das Flores')
,('Região Autónoma dos Açores','Lajes do Pico')
,('Região Autónoma dos Açores','Madalena')
,('Região Autónoma dos Açores','Nordeste')
,('Região Autónoma dos Açores','Ponta Delgada')
,('Região Autónoma dos Açores','Povoação')
,('Região Autónoma dos Açores','Praia da Vitória')
,('Região Autónoma dos Açores','Ribeira Grande')
,('Região Autónoma dos Açores','Santa Cruz da Graciosa')
,('Região Autónoma dos Açores','Santa Cruz das Flores')
,('Região Autónoma dos Açores','São Roque do Pico')
,('Região Autónoma dos Açores','Velas')
,('Região Autónoma dos Açores','Vila do Porto')
,('Região Autónoma dos Açores','Vila Franca do Campo')
,('Região Autónoma da Madeira','Calheta')
,('Região Autónoma da Madeira','Câmara de Lobos')
,('Região Autónoma da Madeira','Funchal')
,('Região Autónoma da Madeira','Machico')
,('Região Autónoma da Madeira','Ponta do Sol')
,('Região Autónoma da Madeira','Porto Moniz')
,('Região Autónoma da Madeira','Porto Santo')
,('Região Autónoma da Madeira','Ribeira Brava')
,('Região Autónoma da Madeira','Santa Cruz')
,('Região Autónoma da Madeira','Santana')
,('Região Autónoma da Madeira','São Vicente')
